#!/usr/bin/perl

$fred[0] = "yabba";
$fred[1] = "dabba";
$fred[2] = "doo";

@array = 5..9;
$fred = pop(@array);
$barney = pop @array;

pop @array;

@tes = qw(pebbles dino fred barney betty);
@removed = splice @tes, 2;

print @removed;



@num = 1..100;

@snum = splice @num,10,50;

#print @snum;

@rocks = qw{ flintstone slate rubble };
print "quartz @rocks limestone\n";

foreach $rock (qw/ bedrock slate lava /) {
	print "One rock is $rock \n";
	}

@test = qw/ bedrock slate lava /;

foreach $rock (@test) {
	$rock = "aaaa$rock";
	$rock .= "\n";

}

print @test;
